Router.map(function(){
    this.route("about", {path:"/about"})
    this.route("chooseUserclass", {path: "/chooseUserclass"})
    this.route("homeBlind", {path:"/homeBlind"})
    this.route("homeHelper", {path: "/homeHelper"})
    this.route("login", {path:"/"})
    this.route("newQuestion", {path: "/newQuestion"})
    this.route("profile", {path: "/profile"})
    this.route("userDeleted", {path: "/userDeleted"})
})